# Generated by Django 6.0.3 on 2026-04-07 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alert',
        ),
    ]
